
spring:
  profiles:
    active: dev
  thymeleaf:
      mode: HTML
  devtools:
    restart:
      trigger-file: .trigger

book:
  name: 我的世界
  author: 付强
  isbn: ${random.uuid}
  description: ${book.name}, 这本书还不错



# 配置文件yml文件命名格式 application-{name}.yml